2025-04-12 21:47:56,256 - INFO - Iniciando processamento do arquivo
2025-04-12 21:53:49,857 - INFO - Iniciando processamento do arquivo
2025-04-12 21:54:06,879 - INFO - Iniciando processamento do arquivo
2025-04-12 21:58:03,833 - INFO - Iniciando processamento do arquivo
2025-04-12 21:58:03,873 - INFO - Data de hoje: 2025-04-12, Data de amanhã: 2025-04-13
2025-04-12 21:58:04,096 - INFO - Leitura da aba CHGs concluída: 1036 linhas
2025-04-12 21:58:04,151 - INFO - Leitura da aba CHGs II concluída: 92 linhas
2025-04-12 21:58:04,154 - INFO - Total de linhas após concatenação: 1128
2025-04-12 21:58:04,155 - INFO - Tipo de dados na coluna 'Data de início planejada': object
2025-04-12 21:58:04,156 - INFO - A coluna 'Data de início planejada' já contém strings
2025-04-12 21:58:04,159 - ERROR - Erro na conversão de datas: Can only use .dt accessor with datetimelike values
2025-04-12 21:58:04,211 - ERROR - Detalhes do erro: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\generate_chg_report.py", line 211, in processar_dados
    df['data_inicio_str'] = df['Data de início planejada'].dt.strftime('%Y-%m-%d')
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\accessors.py", line 512, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values

2025-04-12 22:01:09,703 - INFO - Iniciando processamento do arquivo
2025-04-12 22:01:09,742 - INFO - Data de hoje: 2025-04-12, Data de amanhã: 2025-04-13
2025-04-12 22:01:09,923 - INFO - Leitura da aba CHGs concluída: 1036 linhas
2025-04-12 22:01:09,980 - INFO - Leitura da aba CHGs II concluída: 92 linhas
2025-04-12 22:01:09,981 - INFO - Total de linhas após concatenação: 1128
2025-04-12 22:01:09,983 - INFO - Tipo de dados na coluna 'Data de início planejada': object
2025-04-12 22:01:09,983 - INFO - A coluna 'Data de início planejada' já contém strings
2025-04-12 22:01:09,985 - INFO - Conversão de strings para datetime concluída
2025-04-12 22:01:09,990 - INFO - Criação da coluna 'data_inicio_str' concluída
2025-04-12 22:01:09,990 - INFO - Criação da coluna 'hora_inicio' concluída
2025-04-12 22:01:09,992 - INFO - Amostra de dados após conversão: {'Data de início planejada': {0: Timestamp('2025-01-06 15:00:00'), 1: Timestamp('2025-01-06 15:30:00'), 2: Timestamp('2025-01-06 17:00:00')}, 'data_inicio_str': {0: '2025-01-06', 1: '2025-01-06', 2: '2025-01-06'}, 'hora_inicio': {0: 15, 1: 15, 2: 17}}
2025-04-12 22:01:09,995 - INFO - Atenção: 1 valores de data de término não puderam ser convertidos
2025-04-12 22:01:09,996 - INFO - Linhas com datas de término nulas removidas. Restantes: 1127
2025-04-12 22:01:09,997 - INFO - Filtro para hoje criado: 6 linhas
2025-04-12 22:01:09,998 - INFO - Filtro para amanhã criado: 19 linhas
2025-04-12 22:01:09,999 - INFO - Filtro para 'Enviar Keep' criado: 377 linhas
2025-04-12 22:01:10,000 - INFO - CHGs encontradas (hoje a partir das 17:00 e amanhã até 04:00): 1
2025-04-12 23:29:04,134 - ERROR - Erro no processamento do JSON: gerar_relatorio() takes 1 positional argument but 2 were given
2025-04-12 23:29:04,136 - ERROR - Detalhes do erro: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\generate_chg_report.py", line 654, in <module>
    relatorio = gerar_relatorio(json_data, data_para_relatorio)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: gerar_relatorio() takes 1 positional argument but 2 were given

2025-04-14 22:34:25,014 - INFO - Iniciando processamento do arquivo
2025-04-14 22:34:27,275 - INFO - Data de hoje: 2025-04-14, Data de amanhã: 2025-04-15
2025-04-14 22:34:27,527 - INFO - Leitura da aba CHGs concluída: 1055 linhas
2025-04-14 22:34:27,593 - INFO - Leitura da aba CHGs II concluída: 92 linhas
2025-04-14 22:34:27,604 - INFO - Total de linhas após concatenação: 1147
2025-04-14 22:34:27,607 - INFO - Tipo de dados na coluna 'Data de início planejada': object
2025-04-14 22:34:27,607 - INFO - A coluna 'Data de início planejada' já contém strings
2025-04-14 22:34:27,615 - INFO - Conversão de strings para datetime concluída
2025-04-14 22:34:27,619 - INFO - Criação da coluna 'data_inicio_str' concluída
2025-04-14 22:34:27,620 - INFO - Criação da coluna 'hora_inicio' concluída
2025-04-14 22:34:27,622 - INFO - Amostra de dados após conversão: {'Data de início planejada': {0: Timestamp('2025-01-06 15:00:00'), 1: Timestamp('2025-01-06 15:30:00'), 2: Timestamp('2025-01-06 17:00:00')}, 'data_inicio_str': {0: '2025-01-06', 1: '2025-01-06', 2: '2025-01-06'}, 'hora_inicio': {0: 15, 1: 15, 2: 17}}
2025-04-14 22:34:27,625 - INFO - Atenção: 1 valores de data de término não puderam ser convertidos
2025-04-14 22:34:27,627 - INFO - Linhas com datas de término nulas removidas. Restantes: 1146
2025-04-14 22:34:27,629 - INFO - Filtro para hoje criado: 0 linhas
2025-04-14 22:34:27,629 - INFO - Filtro para amanhã criado: 4 linhas
2025-04-14 22:34:27,630 - INFO - Filtro para 'Enviar Keep' criado: 379 linhas
2025-04-14 22:34:27,632 - INFO - CHGs encontradas (hoje a partir das 17:00 e amanhã até 04:00): 2
2025-04-16 22:10:39,844 - INFO - Iniciando processamento do arquivo
2025-04-16 22:10:42,181 - INFO - Data de hoje: 2025-04-16, Data de amanhã: 2025-04-17
2025-04-16 22:10:42,404 - INFO - Leitura da aba CHGs concluída: 1071 linhas
2025-04-16 22:10:42,474 - INFO - Leitura da aba CHGs II concluída: 97 linhas
2025-04-16 22:10:42,478 - INFO - Total de linhas após concatenação: 1168
2025-04-16 22:10:42,480 - INFO - Tipo de dados na coluna 'Data de início planejada': object
2025-04-16 22:10:42,480 - INFO - A coluna 'Data de início planejada' já contém strings
2025-04-16 22:10:42,483 - INFO - Conversão de strings para datetime concluída
2025-04-16 22:10:42,483 - INFO - Atenção: 1 valores não puderam ser convertidos para data
2025-04-16 22:10:42,484 - INFO - Linhas com datas nulas removidas. Restantes: 1167
2025-04-16 22:10:42,487 - INFO - Criação da coluna 'data_inicio_str' concluída
2025-04-16 22:10:42,487 - INFO - Criação da coluna 'hora_inicio' concluída
2025-04-16 22:10:42,488 - INFO - Amostra de dados após conversão: {'Data de início planejada': {0: Timestamp('2025-01-06 15:00:00'), 1: Timestamp('2025-01-06 15:30:00'), 2: Timestamp('2025-01-06 17:00:00')}, 'data_inicio_str': {0: '2025-01-06', 1: '2025-01-06', 2: '2025-01-06'}, 'hora_inicio': {0: 15, 1: 15, 2: 17}}
2025-04-16 22:10:42,490 - INFO - Atenção: 1 valores de data de término não puderam ser convertidos
2025-04-16 22:10:42,491 - INFO - Linhas com datas de término nulas removidas. Restantes: 1166
2025-04-16 22:10:42,492 - INFO - Filtro para hoje criado: 2 linhas
2025-04-16 22:10:42,492 - INFO - Filtro para amanhã criado: 8 linhas
2025-04-16 22:10:42,494 - INFO - Filtro para 'Enviar Keep' criado: 396 linhas
2025-04-16 22:10:42,496 - INFO - CHGs encontradas (hoje a partir das 17:00 e amanhã até 04:00): 3
2025-04-22 21:11:51,067 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 21:11:51,067 - INFO - Processando aba Full Web
2025-04-22 21:11:51,105 - ERROR - Erro ao processar aba Full Web: Worksheet named 'Full Web' not found
2025-04-22 21:11:51,144 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 48, in processar_testes
    df = pd.read_excel(
         ^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 490, in read_excel
    data = io.parse(
           ^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 1734, in parse
    return self._reader.parse(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 760, in parse
    sheet = self.get_sheet_by_name(asheetname)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 577, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 602, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'Full Web' not found

2025-04-22 21:11:51,145 - INFO - Processando aba Priorizado
2025-04-22 21:11:51,168 - ERROR - Erro ao processar aba Priorizado: Worksheet named 'Priorizado' not found
2025-04-22 21:11:51,169 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 48, in processar_testes
    df = pd.read_excel(
         ^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 490, in read_excel
    data = io.parse(
           ^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 1734, in parse
    return self._reader.parse(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 760, in parse
    sheet = self.get_sheet_by_name(asheetname)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 577, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 602, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'Priorizado' not found

2025-04-22 21:11:51,169 - ERROR - Nenhuma aba válida encontrada no caderno de testes!
2025-04-22 21:11:51,169 - ERROR - Erro crítico no processamento de testes: Nenhuma aba válida encontrada no caderno de testes!
2025-04-22 21:11:51,169 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 74, in processar_testes
    raise Exception(msg)
Exception: Nenhuma aba válida encontrada no caderno de testes!

2025-04-22 21:11:51,170 - ERROR - Erro no processamento de testes: Erro ao processar testes: Nenhuma aba válida encontrada no caderno de testes!
2025-04-22 21:11:51,171 - ERROR - Detalhes do erro: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 74, in processar_testes
    raise Exception(msg)
Exception: Nenhuma aba válida encontrada no caderno de testes!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor_page.py", line 101, in render_test_processor_page
    resultado, qtd_registros = processar_testes(
                               ^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 149, in processar_testes
    raise Exception(f"Erro ao processar testes: {str(e)}")
Exception: Erro ao processar testes: Nenhuma aba válida encontrada no caderno de testes!

2025-04-22 21:12:09,466 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 21:12:09,466 - INFO - Processando aba Full Web
2025-04-22 21:12:09,498 - ERROR - Erro ao processar aba Full Web: Worksheet named 'Full Web' not found
2025-04-22 21:12:09,499 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 48, in processar_testes
    df = pd.read_excel(
         ^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 490, in read_excel
    data = io.parse(
           ^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 1734, in parse
    return self._reader.parse(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 760, in parse
    sheet = self.get_sheet_by_name(asheetname)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 577, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 602, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'Full Web' not found

2025-04-22 21:12:09,499 - INFO - Processando aba Priorizado
2025-04-22 21:12:09,521 - ERROR - Erro ao processar aba Priorizado: Worksheet named 'Priorizado' not found
2025-04-22 21:12:09,521 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 48, in processar_testes
    df = pd.read_excel(
         ^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 490, in read_excel
    data = io.parse(
           ^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 1734, in parse
    return self._reader.parse(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 760, in parse
    sheet = self.get_sheet_by_name(asheetname)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 577, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\excel\_base.py", line 602, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'Priorizado' not found

2025-04-22 21:12:09,521 - ERROR - Nenhuma aba válida encontrada no caderno de testes!
2025-04-22 21:12:09,521 - ERROR - Erro crítico no processamento de testes: Nenhuma aba válida encontrada no caderno de testes!
2025-04-22 21:12:09,521 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 74, in processar_testes
    raise Exception(msg)
Exception: Nenhuma aba válida encontrada no caderno de testes!

2025-04-22 21:12:09,523 - ERROR - Erro no processamento de testes: Erro ao processar testes: Nenhuma aba válida encontrada no caderno de testes!
2025-04-22 21:12:09,524 - ERROR - Detalhes do erro: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 74, in processar_testes
    raise Exception(msg)
Exception: Nenhuma aba válida encontrada no caderno de testes!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor_page.py", line 101, in render_test_processor_page
    resultado, qtd_registros = processar_testes(
                               ^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 149, in processar_testes
    raise Exception(f"Erro ao processar testes: {str(e)}")
Exception: Erro ao processar testes: Nenhuma aba válida encontrada no caderno de testes!

2025-04-22 21:15:32,093 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 21:15:32,093 - INFO - Processando aba Caderno App Vivo
2025-04-22 21:15:33,698 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 21:15:33,698 - INFO - Processando aba Caderno Web B2C
2025-04-22 21:15:33,922 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 21:15:33,925 - INFO - Total de linhas combinadas: 14922
2025-04-22 21:15:33,938 - INFO - Linhas com status válido: 0
2025-04-22 21:15:33,938 - INFO - Nenhum teste com status válido encontrado para processar!
2025-04-22 21:15:33,938 - ERROR - Erro crítico no processamento de testes: Nenhum teste com status válido encontrado para processar!
2025-04-22 21:15:33,939 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 88, in processar_testes
    raise Exception(msg)
Exception: Nenhum teste com status válido encontrado para processar!

2025-04-22 21:15:33,940 - ERROR - Erro no processamento de testes: Erro ao processar testes: Nenhum teste com status válido encontrado para processar!
2025-04-22 21:15:33,940 - ERROR - Detalhes do erro: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 88, in processar_testes
    raise Exception(msg)
Exception: Nenhum teste com status válido encontrado para processar!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor_page.py", line 101, in render_test_processor_page
    resultado, qtd_registros = processar_testes(
                               ^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 149, in processar_testes
    raise Exception(f"Erro ao processar testes: {str(e)}")
Exception: Erro ao processar testes: Nenhum teste com status válido encontrado para processar!

2025-04-22 21:18:37,548 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 21:18:37,548 - INFO - Processando aba Caderno App Vivo
2025-04-22 21:18:39,308 - INFO - Colunas encontradas na aba Caderno App Vivo: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste QD, Notas QD, Observação QD, Status Automação, Observação Automação, Chave_Cenário, STATUS_AUTOMAÇÃO2
2025-04-22 21:18:39,308 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:18:39,323 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 21:18:39,323 - INFO - Processando aba Caderno Web B2C
2025-04-22 21:18:39,553 - INFO - Colunas encontradas na aba Caderno Web B2C: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste, Notas QD, Observação QD
2025-04-22 21:18:39,553 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:18:39,553 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 21:18:39,553 - ERROR - Erro crítico no processamento de testes: Reindexing only valid with uniquely valued Index objects
2025-04-22 21:18:39,583 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 127, in processar_testes
    df_combined = pd.concat(dfs, axis=0, ignore_index=True, sort=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\reshape\concat.py", line 381, in concat
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\reshape\concat.py", line 612, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3904, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

2025-04-22 21:18:39,583 - ERROR - Erro no processamento de testes: Erro ao processar testes: Reindexing only valid with uniquely valued Index objects
2025-04-22 21:18:39,587 - ERROR - Detalhes do erro: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 127, in processar_testes
    df_combined = pd.concat(dfs, axis=0, ignore_index=True, sort=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\reshape\concat.py", line 381, in concat
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\reshape\concat.py", line 612, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3904, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor_page.py", line 116, in render_test_processor_page
    resultado, qtd_registros = processar_testes(
                               ^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 215, in processar_testes
    raise Exception(f"Erro ao processar testes: {str(e)}")
Exception: Erro ao processar testes: Reindexing only valid with uniquely valued Index objects

2025-04-22 21:19:10,445 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 21:19:10,445 - INFO - Processando aba Caderno App Vivo
2025-04-22 21:19:12,048 - INFO - Colunas encontradas na aba Caderno App Vivo: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste QD, Notas QD, Observação QD, Status Automação, Observação Automação, Chave_Cenário, STATUS_AUTOMAÇÃO2
2025-04-22 21:19:12,048 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:19:12,058 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 21:19:12,058 - INFO - Processando aba Caderno Web B2C
2025-04-22 21:19:12,301 - INFO - Colunas encontradas na aba Caderno Web B2C: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste, Notas QD, Observação QD
2025-04-22 21:19:12,301 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:19:12,302 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 21:19:12,302 - ERROR - Erro crítico no processamento de testes: Reindexing only valid with uniquely valued Index objects
2025-04-22 21:19:12,303 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 127, in processar_testes
    df_combined = pd.concat(dfs, axis=0, ignore_index=True, sort=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\reshape\concat.py", line 381, in concat
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\reshape\concat.py", line 612, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3904, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

2025-04-22 21:19:12,303 - ERROR - Erro no processamento de testes: Erro ao processar testes: Reindexing only valid with uniquely valued Index objects
2025-04-22 21:19:12,304 - ERROR - Detalhes do erro: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 127, in processar_testes
    df_combined = pd.concat(dfs, axis=0, ignore_index=True, sort=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\reshape\concat.py", line 381, in concat
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\reshape\concat.py", line 612, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py", line 3904, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor_page.py", line 116, in render_test_processor_page
    resultado, qtd_registros = processar_testes(
                               ^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 215, in processar_testes
    raise Exception(f"Erro ao processar testes: {str(e)}")
Exception: Erro ao processar testes: Reindexing only valid with uniquely valued Index objects

2025-04-22 21:22:16,133 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 21:22:16,134 - INFO - Processando aba Caderno App Vivo
2025-04-22 21:22:17,867 - INFO - Colunas encontradas na aba Caderno App Vivo: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste QD, Notas QD, Observação QD, Status Automação, Observação Automação, Chave_Cenário, STATUS_AUTOMAÇÃO2
2025-04-22 21:22:17,867 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:22:17,979 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 21:22:17,979 - INFO - Processando aba Caderno Web B2C
2025-04-22 21:22:18,219 - INFO - Colunas encontradas na aba Caderno Web B2C: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste, Notas QD, Observação QD
2025-04-22 21:22:18,219 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:22:18,225 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 21:22:18,240 - INFO - Total de linhas combinadas: 14922
2025-04-22 21:22:18,248 - INFO - Valores únicos de status encontrados: Validar, Passed, Not Executed, nan, Ativo
2025-04-22 21:22:18,253 - ERROR - Erro crítico no processamento de testes: Cannot mask with non-boolean array containing NA / NaN values
2025-04-22 21:22:18,276 - ERROR - Detalhes: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 167, in processar_testes
    df_combined.loc[df_combined['Status'].str.lower().str.contains('not executed'), 'Status'] = 'Not Executed'
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 814, in __setitem__
    indexer = self._get_setitem_indexer(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 697, in _get_setitem_indexer
    return self._convert_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 896, in _convert_tuple
    keyidx = [self._convert_to_indexer(k, axis=i) for i, k in enumerate(key)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 896, in <listcomp>
    keyidx = [self._convert_to_indexer(k, axis=i) for i, k in enumerate(key)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 1392, in _convert_to_indexer
    if com.is_bool_indexer(key):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\common.py", line 135, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values

2025-04-22 21:22:18,278 - ERROR - Erro no processamento de testes: Erro ao processar testes: Cannot mask with non-boolean array containing NA / NaN values
2025-04-22 21:22:18,279 - ERROR - Detalhes do erro: Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 167, in processar_testes
    df_combined.loc[df_combined['Status'].str.lower().str.contains('not executed'), 'Status'] = 'Not Executed'
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 814, in __setitem__
    indexer = self._get_setitem_indexer(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 697, in _get_setitem_indexer
    return self._convert_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 896, in _convert_tuple
    keyidx = [self._convert_to_indexer(k, axis=i) for i, k in enumerate(key)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 896, in <listcomp>
    keyidx = [self._convert_to_indexer(k, axis=i) for i, k in enumerate(key)]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexing.py", line 1392, in _convert_to_indexer
    if com.is_bool_indexer(key):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\common.py", line 135, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: Cannot mask with non-boolean array containing NA / NaN values

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matee\Music\chgs-main2\test_processor_page.py", line 116, in render_test_processor_page
    resultado, qtd_registros = processar_testes(
                               ^^^^^^^^^^^^^^^^^
  File "C:\Users\matee\Music\chgs-main2\test_processor.py", line 238, in processar_testes
    raise Exception(f"Erro ao processar testes: {str(e)}")
Exception: Erro ao processar testes: Cannot mask with non-boolean array containing NA / NaN values

2025-04-22 21:27:27,919 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 21:27:27,919 - INFO - Processando aba Caderno App Vivo
2025-04-22 21:27:29,843 - INFO - Colunas encontradas na aba Caderno App Vivo: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste QD, Notas QD, Observação QD, Status Automação, Observação Automação, Chave_Cenário, STATUS_AUTOMAÇÃO2
2025-04-22 21:27:29,843 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:27:29,865 - INFO - Valores nulos na coluna Status tratados
2025-04-22 21:27:29,974 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 21:27:29,974 - INFO - Processando aba Caderno Web B2C
2025-04-22 21:27:30,222 - INFO - Colunas encontradas na aba Caderno Web B2C: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste, Notas QD, Observação QD
2025-04-22 21:27:30,222 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:27:30,224 - INFO - Valores nulos na coluna Status tratados
2025-04-22 21:27:30,229 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 21:27:30,242 - INFO - Total de linhas combinadas: 14922
2025-04-22 21:27:30,243 - INFO - Verificando valores nulos na coluna Status
2025-04-22 21:27:30,245 - INFO - Tipos de dados na coluna Status: ['str']
2025-04-22 21:27:30,254 - INFO - Valores únicos de status encontrados: Validar, Passed, Not Executed, , Ativo
2025-04-22 21:27:30,264 - INFO - Adicionando novo status válido: 'Validar'
2025-04-22 21:27:30,265 - INFO - Adicionando novo status válido: 'Ativo'
2025-04-22 21:27:30,274 - INFO - Linhas com status válido: 14479
2025-04-22 21:27:32,392 - INFO - Data adicionada aos registros: 22/04/2025
2025-04-22 21:27:32,392 - INFO - Carregando arquivo diário
2025-04-22 21:27:52,686 - INFO - Aba B2C encontrada e carregada
2025-04-22 21:27:54,142 - INFO - Última linha com dados: 151791
2025-04-22 21:27:54,331 - INFO - Cabeçalho obtido: 14 colunas
2025-04-22 21:27:54,337 - INFO - Adicionando 14479 novos registros
2025-04-22 21:28:20,951 - INFO - Processamento concluído com sucesso: 14479 registros adicionados
2025-04-22 21:33:43,949 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 21:33:43,949 - INFO - Processando aba Caderno App Vivo
2025-04-22 21:33:45,546 - INFO - Colunas encontradas na aba Caderno App Vivo: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste QD, Notas QD, Observação QD, Status Automação, Observação Automação, Chave_Cenário, STATUS_AUTOMAÇÃO2
2025-04-22 21:33:45,546 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:33:45,570 - INFO - Valores nulos na coluna Status tratados
2025-04-22 21:33:45,658 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 21:33:45,658 - INFO - Processando aba Caderno Web B2C
2025-04-22 21:33:45,895 - INFO - Colunas encontradas na aba Caderno Web B2C: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste, Notas QD, Observação QD
2025-04-22 21:33:45,896 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 21:33:45,897 - INFO - Valores nulos na coluna Status tratados
2025-04-22 21:33:45,901 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 21:33:45,916 - INFO - Total de linhas combinadas: 14922
2025-04-22 21:33:45,916 - INFO - Verificando valores nulos na coluna Status
2025-04-22 21:33:45,919 - INFO - Tipos de dados na coluna Status: ['str']
2025-04-22 21:33:45,926 - INFO - Valores únicos de status encontrados: Validar, Passed, Not Executed, , Ativo
2025-04-22 21:33:45,936 - INFO - Status após normalização: Validar, Passed, Not Executed, , Ativo
2025-04-22 21:33:45,936 - INFO - Filtrando apenas pelos status: Passed, Not Executed, Failed
2025-04-22 21:33:45,940 - INFO - Linhas com status válido: 886 de 14922 total
2025-04-22 21:33:45,941 - INFO - Data adicionada aos registros: 22/04/2025
2025-04-22 21:33:45,941 - INFO - Carregando arquivo diário
2025-04-22 21:34:10,449 - INFO - Aba B2C encontrada e carregada
2025-04-22 21:34:12,572 - INFO - Última linha com dados: 166270
2025-04-22 21:34:12,727 - INFO - Cabeçalho obtido: 14 colunas
2025-04-22 21:34:12,728 - INFO - Adicionando 886 novos registros
2025-04-22 21:34:37,226 - INFO - Processamento concluído com sucesso: 886 registros adicionados
2025-04-22 22:08:22,916 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 22:08:22,916 - INFO - Processando aba Caderno App Vivo
2025-04-22 22:08:24,563 - INFO - Colunas encontradas na aba Caderno App Vivo: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste QD, Notas QD, Observação QD, Status Automação, Observação Automação, Chave_Cenário, STATUS_AUTOMAÇÃO2
2025-04-22 22:08:24,563 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 22:08:24,581 - INFO - Valores nulos na coluna Status tratados
2025-04-22 22:08:24,677 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 22:08:24,678 - INFO - Processando aba Caderno Web B2C
2025-04-22 22:08:24,918 - INFO - Colunas encontradas na aba Caderno Web B2C: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste, Notas QD, Observação QD
2025-04-22 22:08:24,918 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 22:08:24,920 - INFO - Valores nulos na coluna Status tratados
2025-04-22 22:08:24,924 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 22:08:24,940 - INFO - Total de linhas combinadas: 14922
2025-04-22 22:08:24,940 - INFO - Verificando valores nulos na coluna Status
2025-04-22 22:08:24,942 - INFO - Tipos de dados na coluna Status: ['str']
2025-04-22 22:08:24,950 - INFO - Valores únicos de status encontrados: Validar, Passed, Not Executed, , Ativo
2025-04-22 22:08:24,961 - INFO - Status após normalização: Validar, Passed, Not Executed, , Ativo
2025-04-22 22:08:24,961 - INFO - Status indesejados encontrados e que serão excluídos: Validar, , Ativo
2025-04-22 22:08:24,961 - INFO - Status 'A validar' encontrados e que serão excluídos: Validar
2025-04-22 22:08:24,961 - INFO - Filtrando apenas pelos status: Passed, Not Executed, Failed
2025-04-22 22:08:24,971 - INFO - Excluindo 13541 registros com status 'Validar'
2025-04-22 22:08:24,979 - INFO - Linhas com status válido: 886 de 1381 total
2025-04-22 22:08:24,980 - INFO - Status após filtragem final: Passed, Not Executed
2025-04-22 22:08:24,980 - INFO - Data adicionada aos registros: 22/04/2025
2025-04-22 22:08:24,980 - INFO - Carregando arquivo diário
2025-04-22 22:08:43,231 - INFO - Aba B2C encontrada e carregada
2025-04-22 22:08:45,341 - INFO - Última linha com dados: 151791
2025-04-22 22:08:45,537 - INFO - Cabeçalho obtido: 14 colunas
2025-04-22 22:08:45,538 - INFO - Adicionando 886 novos registros
2025-04-22 22:09:09,902 - INFO - Processamento concluído com sucesso: 886 registros adicionados
2025-04-22 22:34:24,637 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 22:34:24,639 - INFO - Processando aba Caderno App Vivo
2025-04-22 22:34:24,941 - INFO - Iniciando processamento de arquivos de teste
2025-04-22 22:34:24,942 - INFO - Processando aba Caderno App Vivo
2025-04-22 22:34:28,181 - INFO - Colunas encontradas na aba Caderno App Vivo: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste QD, Notas QD, Observação QD, Status Automação, Observação Automação, Chave_Cenário, STATUS_AUTOMAÇÃO2
2025-04-22 22:34:28,181 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 22:34:28,223 - INFO - Valores nulos na coluna Status tratados
2025-04-22 22:34:28,376 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 22:34:28,378 - INFO - Processando aba Caderno Web B2C
2025-04-22 22:34:28,709 - INFO - Colunas encontradas na aba Caderno App Vivo: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste QD, Notas QD, Observação QD, Status Automação, Observação Automação, Chave_Cenário, STATUS_AUTOMAÇÃO2
2025-04-22 22:34:28,709 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 22:34:28,731 - INFO - Valores nulos na coluna Status tratados
2025-04-22 22:34:28,876 - INFO - Aba Caderno App Vivo processada: 14464 linhas
2025-04-22 22:34:28,877 - INFO - Processando aba Caderno Web B2C
2025-04-22 22:34:29,061 - INFO - Colunas encontradas na aba Caderno Web B2C: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste, Notas QD, Observação QD
2025-04-22 22:34:29,061 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 22:34:29,082 - INFO - Valores nulos na coluna Status tratados
2025-04-22 22:34:29,088 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 22:34:29,115 - INFO - Total de linhas combinadas: 14922
2025-04-22 22:34:29,115 - INFO - Verificando valores nulos na coluna Status
2025-04-22 22:34:29,121 - INFO - Tipos de dados na coluna Status: ['str']
2025-04-22 22:34:29,138 - INFO - Valores únicos de status encontrados: Validar, Passed, Not Executed, , Ativo
2025-04-22 22:34:29,194 - INFO - Status após normalização: Validar, Passed, Not Executed, , Ativo
2025-04-22 22:34:29,194 - INFO - Status indesejados encontrados e que serão excluídos: Validar, , Ativo
2025-04-22 22:34:29,196 - INFO - Status 'A validar' encontrados e que serão excluídos: Validar
2025-04-22 22:34:29,198 - INFO - Filtrando apenas pelos status: Passed, Not Executed, Failed
2025-04-22 22:34:29,210 - INFO - Excluindo 13541 registros com status 'Validar'
2025-04-22 22:34:29,230 - INFO - Linhas com status válido: 886 de 1381 total
2025-04-22 22:34:29,230 - INFO - Status após filtragem final: Passed, Not Executed
2025-04-22 22:34:29,231 - INFO - Data adicionada aos registros: 22/04/2025
2025-04-22 22:34:29,231 - INFO - Carregando arquivo diário
2025-04-22 22:34:29,333 - INFO - Colunas encontradas na aba Caderno Web B2C: ID Fluxo, Planejamento, Frente, Caderno, Canal, Plataforma, Tipo de Plano, Plano, Característica da massa, Entrypoint, Funcionalidade, Cenário, Resultado esperado, Prioridade, Status, Periodicidade , Observação, Coberto por, Status do Teste, Notas QD, Observação QD
2025-04-22 22:34:29,338 - INFO - Coluna de status encontrada: 'Status'
2025-04-22 22:34:29,345 - INFO - Valores nulos na coluna Status tratados
2025-04-22 22:34:29,361 - INFO - Aba Caderno Web B2C processada: 458 linhas
2025-04-22 22:34:29,383 - INFO - Total de linhas combinadas: 14922
2025-04-22 22:34:29,383 - INFO - Verificando valores nulos na coluna Status
2025-04-22 22:34:29,384 - INFO - Tipos de dados na coluna Status: ['str']
2025-04-22 22:34:29,405 - INFO - Valores únicos de status encontrados: Validar, Passed, Not Executed, , Ativo
2025-04-22 22:34:29,460 - INFO - Status após normalização: Validar, Passed, Not Executed, , Ativo
2025-04-22 22:34:29,474 - INFO - Status indesejados encontrados e que serão excluídos: Validar, , Ativo
2025-04-22 22:34:29,481 - INFO - Status 'A validar' encontrados e que serão excluídos: Validar
2025-04-22 22:34:29,488 - INFO - Filtrando apenas pelos status: Passed, Not Executed, Failed
2025-04-22 22:34:29,515 - INFO - Excluindo 13541 registros com status 'Validar'
2025-04-22 22:34:29,537 - INFO - Linhas com status válido: 886 de 1381 total
2025-04-22 22:34:29,537 - INFO - Status após filtragem final: Passed, Not Executed
2025-04-22 22:34:29,544 - INFO - Data adicionada aos registros: 22/04/2025
2025-04-22 22:34:29,544 - INFO - Carregando arquivo diário
2025-04-22 22:35:08,712 - INFO - Aba B2C encontrada e carregada
2025-04-22 22:35:09,753 - INFO - Aba B2C encontrada e carregada
2025-04-22 22:35:12,954 - INFO - Última linha com dados: 151791
2025-04-22 22:35:13,445 - INFO - Cabeçalho obtido: 14 colunas
2025-04-22 22:35:13,517 - INFO - Adicionando 886 novos registros
2025-04-22 22:35:13,772 - INFO - Última linha com dados: 151791
2025-04-22 22:35:13,997 - INFO - Cabeçalho obtido: 14 colunas
2025-04-22 22:35:14,045 - INFO - Adicionando 886 novos registros
2025-04-22 22:36:02,637 - INFO - Processamento concluído com sucesso: 886 registros adicionados
2025-04-22 22:36:02,649 - INFO - Processamento concluído com sucesso: 886 registros adicionados
